global using Raylib_cs;
global using static Raylib_cs.Raylib;
global using SharpRay.Core;
global using SharpRay.Gui;
global using static SharpRay.Core.Application;
global using Common;
global using static AoC.Program;
global using System.Numerics;
global using SharpRay.Entities;
global using SharpRay.Eventing;
global using Common.Interfaces;
global using System.Collections.Concurrent;
global using Common.Extensions;
global using System.Reflection;